Repository HXQLabs/Helixque, pull requests merged in 2025-10, with the labels that each got.

#49 Generic names in chat window. Peer instead of {username}
  frontend/components/RTC/Chat/chat.tsx
Labels: good first issue, hacktoberfest2025, hacktoberfest-accepted, hacktoberfest, hacktoberfest2025-accepted

#56 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: good first issue, hacktoberfest2025, hacktoberfest-accepted, hacktoberfest, hacktoberfest2025-accepted

#57 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest2025, hacktoberfest-accepted, hacktoberfest, hacktoberfest2025-accepted

#65 Replace IconPlayerSkipForward with IconUserOff for better UX
  frontend/components/RTC/Room.tsx
Labels: good first issue, hacktoberfest2025, hacktoberfest-accepted, hacktoberfest, hacktoberfest2025-accepted

#73 Implement Report Button #7 ; added some features on the CLIENT-SIDE only
  .github/pull_request_template.md
  CONTRIBUTING.md
  frontend/components/RTC/Chat/chat.tsx
  frontend/components/RTC/Room.tsx
  frontend/components/ui/toaster.tsx
Labels: hacktoberfest2025, UI-UX, hacktoberfest-accepted, hacktoberfest, hacktoberfest2025-accepted

#82 Develop
  backend/package-lock.json
  frontend/components/RTC/Chat/chat.tsx
  frontend/components/RTC/ControlBar.tsx
  frontend/components/RTC/Room.tsx
  frontend/components/RTC/TimeoutAlert.tsx
  frontend/components/RTC/VideoGrid.tsx
  frontend/components/RTC/hooks.tsx
  frontend/components/RTC/webrtc-utils.tsx
  frontend/components/ui/toaster.tsx
Labels: hacktoberfest2025, hacktoberfest-accepted, hacktoberfest, hacktoberfest2025-accepted, priority: high

#74 Added custom UI for tooltip
  .github/FUNDING.yml
  frontend/bun.lockb
  frontend/components/RTC/Chat/chat.tsx
  frontend/components/RTC/ControlBar.tsx
  frontend/components/RTC/DeviceCheck.tsx
  frontend/components/RTC/Room.tsx
  frontend/components/ui/tooltip.tsx
Labels: hacktoberfest2025, UI-UX, hacktoberfest-accepted, hacktoberfest, hacktoberfest2025-accepted

#88 Updating the Readme.md file #86 ; docs: enhance README with improved layout and styling
  README.md
Labels: documentation, hacktoberfest2025, hacktoberfest-accepted, hacktoberfest, hacktoberfest2025-accepted

#118 Fixed toast notification message Error permission denied appearing twice
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/code_enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
  README.md
  backend/package-lock.json
  backend/package.json
  backend/tsconfig.json
  frontend/components/RTC/DeviceCheck.tsx
  frontend/components/RTC/Room.tsx
Labels: good first issue, hacktoberfest2025, hacktoberfest-accepted, hacktoberfest, hacktoberfest2025-accepted

#132 fixed: Fix alignment and redesign the meeting join page issue#128
  frontend/components/RTC/DeviceCheck.tsx
Labels: hacktoberfest2025, hacktoberfest-accepted, hacktoberfest, hacktoberfest2025-accepted

#126 Create SECURITY.md
  SECURITY.md
Labels: documentation, hacktoberfest2025, hacktoberfest-accepted, hacktoberfest, hacktoberfest2025-accepted
